/*
 * This file is generated by jOOQ.
*/
package com.lucoo.sky.battle.jooq.tables.records;


import com.lucoo.sky.battle.jooq.tables.Profile;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfileRecord extends UpdatableRecordImpl<ProfileRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = -1769130224;

    /**
     * Setter for <code>config-repository.profile.ID</code>. 编号
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>config-repository.profile.ID</code>. 编号
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>config-repository.profile.profile</code>. 环境
     */
    public void setProfile(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>config-repository.profile.profile</code>. 环境
     */
    public String getProfile() {
        return (String) get(1);
    }

    /**
     * Setter for <code>config-repository.profile.application_id</code>. 应用外键
     */
    public void setApplicationId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>config-repository.profile.application_id</code>. 应用外键
     */
    public Integer getApplicationId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Profile.PROFILE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Profile.PROFILE.PROFILE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Profile.PROFILE.APPLICATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProfile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getApplicationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileRecord value2(String value) {
        setProfile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileRecord value3(Integer value) {
        setApplicationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProfileRecord
     */
    public ProfileRecord() {
        super(Profile.PROFILE);
    }

    /**
     * Create a detached, initialised ProfileRecord
     */
    public ProfileRecord(Integer id, String profile, Integer applicationId) {
        super(Profile.PROFILE);

        set(0, id);
        set(1, profile);
        set(2, applicationId);
    }
}
