/*
 * This file is generated by jOOQ.
*/
package com.lucoo.sky.battle.jooq.tables.records;


import com.lucoo.sky.battle.jooq.tables.Properties;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PropertiesRecord extends UpdatableRecordImpl<PropertiesRecord> implements Record7<Long, Integer, Integer, String, String, String, String> {

    private static final long serialVersionUID = 1459653792;

    /**
     * Setter for <code>config-repository.properties.ID</code>. 编号
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>config-repository.properties.ID</code>. 编号
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>config-repository.properties.application_id</code>.
     */
    public void setApplicationId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>config-repository.properties.application_id</code>.
     */
    public Integer getApplicationId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>config-repository.properties.profile_id</code>.
     */
    public void setProfileId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>config-repository.properties.profile_id</code>.
     */
    public Integer getProfileId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>config-repository.properties.key</code>.
     */
    public void setKey(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>config-repository.properties.key</code>.
     */
    public String getKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>config-repository.properties.raw_value</code>.
     */
    public void setRawValue(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>config-repository.properties.raw_value</code>.
     */
    public String getRawValue() {
        return (String) get(4);
    }

    /**
     * Setter for <code>config-repository.properties.application_name</code>.
     */
    public void setApplicationName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>config-repository.properties.application_name</code>.
     */
    public String getApplicationName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>config-repository.properties.profile_name</code>.
     */
    public void setProfileName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>config-repository.properties.profile_name</code>.
     */
    public String getProfileName() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Integer, Integer, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Integer, Integer, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Properties.PROPERTIES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Properties.PROPERTIES.APPLICATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Properties.PROPERTIES.PROFILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Properties.PROPERTIES.KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Properties.PROPERTIES.RAW_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Properties.PROPERTIES.APPLICATION_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Properties.PROPERTIES.PROFILE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getApplicationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getProfileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getRawValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getApplicationName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getProfileName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertiesRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertiesRecord value2(Integer value) {
        setApplicationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertiesRecord value3(Integer value) {
        setProfileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertiesRecord value4(String value) {
        setKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertiesRecord value5(String value) {
        setRawValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertiesRecord value6(String value) {
        setApplicationName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertiesRecord value7(String value) {
        setProfileName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertiesRecord values(Long value1, Integer value2, Integer value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PropertiesRecord
     */
    public PropertiesRecord() {
        super(Properties.PROPERTIES);
    }

    /**
     * Create a detached, initialised PropertiesRecord
     */
    public PropertiesRecord(Long id, Integer applicationId, Integer profileId, String key, String rawValue, String applicationName, String profileName) {
        super(Properties.PROPERTIES);

        set(0, id);
        set(1, applicationId);
        set(2, profileId);
        set(3, key);
        set(4, rawValue);
        set(5, applicationName);
        set(6, profileName);
    }
}
