/*
 * This file is generated by jOOQ.
*/
package com.lucoo.sky.battle.jooq;


import com.lucoo.sky.battle.jooq.tables.Application;
import com.lucoo.sky.battle.jooq.tables.Idworker;
import com.lucoo.sky.battle.jooq.tables.Profile;
import com.lucoo.sky.battle.jooq.tables.Properties;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in config-repository
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>config-repository.application</code>.
     */
    public static final Application APPLICATION = com.lucoo.sky.battle.jooq.tables.Application.APPLICATION;

    /**
     * The table <code>config-repository.idworker</code>.
     */
    public static final Idworker IDWORKER = com.lucoo.sky.battle.jooq.tables.Idworker.IDWORKER;

    /**
     * The table <code>config-repository.profile</code>.
     */
    public static final Profile PROFILE = com.lucoo.sky.battle.jooq.tables.Profile.PROFILE;

    /**
     * The table <code>config-repository.properties</code>.
     */
    public static final Properties PROPERTIES = com.lucoo.sky.battle.jooq.tables.Properties.PROPERTIES;
}
