/*
 * This file is generated by jOOQ.
*/
package com.lucoo.sky.battle.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Application implements Serializable {

    private static final long serialVersionUID = 747989946;

    private Integer id;
    private String  application;

    public Application() {}

    public Application(Application value) {
        this.id = value.id;
        this.application = value.application;
    }

    public Application(
        Integer id,
        String  application
    ) {
        this.id = id;
        this.application = application;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getApplication() {
        return this.application;
    }

    public void setApplication(String application) {
        this.application = application;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Application (");

        sb.append(id);
        sb.append(", ").append(application);

        sb.append(")");
        return sb.toString();
    }
}
