/*
 * This file is generated by jOOQ.
*/
package com.lucoo.sky.battle.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Idworker implements Serializable {

    private static final long serialVersionUID = -1352005980;

    private Integer id;
    private String  applicationName;
    private String  ip;
    private String  port;
    private Integer datacenterId;
    private Integer workerId;
    private Byte    status;

    public Idworker() {}

    public Idworker(Idworker value) {
        this.id = value.id;
        this.applicationName = value.applicationName;
        this.ip = value.ip;
        this.port = value.port;
        this.datacenterId = value.datacenterId;
        this.workerId = value.workerId;
        this.status = value.status;
    }

    public Idworker(
        Integer id,
        String  applicationName,
        String  ip,
        String  port,
        Integer datacenterId,
        Integer workerId,
        Byte    status
    ) {
        this.id = id;
        this.applicationName = applicationName;
        this.ip = ip;
        this.port = port;
        this.datacenterId = datacenterId;
        this.workerId = workerId;
        this.status = status;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getApplicationName() {
        return this.applicationName;
    }

    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName;
    }

    public String getIp() {
        return this.ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public String getPort() {
        return this.port;
    }

    public void setPort(String port) {
        this.port = port;
    }

    public Integer getDatacenterId() {
        return this.datacenterId;
    }

    public void setDatacenterId(Integer datacenterId) {
        this.datacenterId = datacenterId;
    }

    public Integer getWorkerId() {
        return this.workerId;
    }

    public void setWorkerId(Integer workerId) {
        this.workerId = workerId;
    }

    public Byte getStatus() {
        return this.status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Idworker (");

        sb.append(id);
        sb.append(", ").append(applicationName);
        sb.append(", ").append(ip);
        sb.append(", ").append(port);
        sb.append(", ").append(datacenterId);
        sb.append(", ").append(workerId);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
