/*
 * This file is generated by jOOQ.
*/
package com.lucoo.sky.battle.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Properties implements Serializable {

    private static final long serialVersionUID = -1319885032;

    private Long    id;
    private Integer applicationId;
    private Integer profileId;
    private String  key;
    private String  rawValue;
    private String  applicationName;
    private String  profileName;

    public Properties() {}

    public Properties(Properties value) {
        this.id = value.id;
        this.applicationId = value.applicationId;
        this.profileId = value.profileId;
        this.key = value.key;
        this.rawValue = value.rawValue;
        this.applicationName = value.applicationName;
        this.profileName = value.profileName;
    }

    public Properties(
        Long    id,
        Integer applicationId,
        Integer profileId,
        String  key,
        String  rawValue,
        String  applicationName,
        String  profileName
    ) {
        this.id = id;
        this.applicationId = applicationId;
        this.profileId = profileId;
        this.key = key;
        this.rawValue = rawValue;
        this.applicationName = applicationName;
        this.profileName = profileName;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getApplicationId() {
        return this.applicationId;
    }

    public void setApplicationId(Integer applicationId) {
        this.applicationId = applicationId;
    }

    public Integer getProfileId() {
        return this.profileId;
    }

    public void setProfileId(Integer profileId) {
        this.profileId = profileId;
    }

    public String getKey() {
        return this.key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getRawValue() {
        return this.rawValue;
    }

    public void setRawValue(String rawValue) {
        this.rawValue = rawValue;
    }

    public String getApplicationName() {
        return this.applicationName;
    }

    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName;
    }

    public String getProfileName() {
        return this.profileName;
    }

    public void setProfileName(String profileName) {
        this.profileName = profileName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Properties (");

        sb.append(id);
        sb.append(", ").append(applicationId);
        sb.append(", ").append(profileId);
        sb.append(", ").append(key);
        sb.append(", ").append(rawValue);
        sb.append(", ").append(applicationName);
        sb.append(", ").append(profileName);

        sb.append(")");
        return sb.toString();
    }
}
